wandb_version: 1

batch_size:
  value: 64
cell_type:
  value: rnn
data_path:
  value: c:\Users\sanka\Desktop\DL_Assignment_3\hi
dec_layers:
  value: 1
dropout:
  value: 0.2
embed_dim:
  value: 256
enc_layers:
  value: 1
epochs:
  value: 10
hidden_size:
  value: 512
lang_code:
  value: hi
learning_rate:
  value: 0.0005
teacher_forcing:
  value: 0.5
